/* Automatically generated by po2tbl.sed from normalize.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"\
Usage: %s [OPTION]... [FILE]...\n\
Normalize volume of multiple WAV files\n\
\n\
  -a, --amplitude=AMP  normalize the RMS volume to the target amplitude\n\
                         AMP [default 0.25 or -12dBFS]\n\
  -n, --no-adjust      compute and output the volume adjustment, but\n\
                         don't apply it to any of the files\n\
  -g, --gain=ADJ       don't compute the volume adjustment, just apply\n\
                         adjustment ADJ to the files.  Use the suffix \
\"dB\"\n\
                         to indicate a gain in decibels.\n\
  -b, --batch          batch mode: average the levels of all files given\n\
                         on the command line, and use one adjustment, based\n\
                         on the average level, for all files\n\
  -m, --mix            mix mode: average the levels of all files given\n\
                         on the command line, and normalize volume of\n\
                         each file to the average level\n\
  -t, --threshold=THR  in batch mode, throw out any level values more\n\
                         than THR decibels different from the average.\n\
                         By default, use twice the standard deviation of\n\
                         all the power levels.\n\
  -c, --compression    do dynamic range compression, instead of clipping.\n\
      --peak           adjust using peak levels instead of RMS levels.\n\
                         Each file will be adjusted so that its maximum\n\
                         sample is at full scale.\n\
  -v, --verbose        increase verbosity\n\
  -q, --quiet          quiet (decrease verbosity to zero)\n\
  -V, --version        display version information and exit\n\
  -h, --help           display this help and exit\n\
\n\
Report bugs to <cvaill@cs.columbia.edu>.\n", 2},
  {"%s: Warning: assuming you meant -%s...\n", 3},
  {"%s: error: the -m and -b options are mutually exclusive\n", 4},
  {"%s: error: -m and -b can't be used with the --peak option\n", 5},
  {"%s: Warning: stdin specified on command line, not adjusting files\n", 6},
  {"%s: file %s: %s\n", 7},
  {"%s: no files!\n", 8},
  {"%-12.6f average level\n", 9},
  {"%-8.4fdBFS average level\n", 10},
  {"Average level: %0.4f\n", 11},
  {"Average level: %0.4fdBFS\n", 12},
  {"Files are already normalized, not adjusting...\n", 13},
  {"Applying adjustment of %fdB...\n", 14},
  {"Applying adjustment of %f...\n", 15},
  {"Applying adjustment of %0.2fdB...\n", 16},
  {"%s: error opening %s: %s\n", 17},
  {"%s already normalized, not adjusting...\n", 18},
  {"Applying adjustment of %0.2fdB to %s...\n", 19},
  {"%s: error opening temp file: %s\n", 20},
  {"%s: error applying adjustment to %s: %s\n", 21},
  {"%s: error moving %s to %s: %s\n", 22},
  {"%-12f volume adjustment\n", 23},
  {"%-12s volume adjustment\n", 24},
  {"Computing levels...\n", 25},
  {"  level        peak\n", 26},
  {"  level        peak         gain\n", 27},
  {"%s: error reading %s: %s\n", 28},
  {"File %s has zero power, ignoring...\n", 29},
  {"Level for %s: %0.4f (%0.4f peak)\n", 30},
  {"Level for %s: %0.4fdBFS (%0.4fdBFS peak)\n", 31},
  {"Standard deviation is %0.2f dB\n", 32},
  {"Throwing out level of %0.4f (different by %0.2fdB)\n", 33},
  {"Throwing out level of %0.4fdBFS (different by %0.2fdB)\n", 34},
  {"%s: all files ignored, try using -t 100\n", 35},
  {" %s  --%% done, ETA --:--:-- (batch  --%% done, ETA --:--:--)", 36},
  {" %s  --%% done, ETA --:--:-- (batch %3.0f%% done, ETA --:--:--)", 37},
  {"\
 %s %3.0f%% done, ETA %02d:%02d:%02d (batch %3.0f%% done, ETA %02d:%02d:%02d)", 38},
  {"%s: I don't know what to do with %d bytes per sample\n", 39},
  {"%s: error reading riff chunk\n", 40},
  {"%s: not a RIFF WAV file\n", 41},
  {"%s: no format chunk found\n", 42},
  {"%s: this is a non-PCM WAV file\n", 43},
  {"%s: more than 32 bits per sample not implemented\n", 44},
  {"%s: no data chunk found\n", 45},
  {"%s: error making riff object\n", 46},
  {"%s: error getting wav data\n", 47},
  {"%s: failed fdopen: %s\n", 48},
  {"%s: read failed: %s\n", 49},
  {"%s: write failed: %s\n", 50},
  {"%s: failed fwrite: %s\n", 51},
  {"%s: failed fflush: %s\n", 52},
  {"%s: %d clippings performed, %.4f%% loss\n", 53},
  {"%s: Warning: lost %0.2f%% of data due to clipping              \n", 54},
  {"%s: unable to malloc\n", 55},
  {"%s: option `%s' is ambiguous\n", 56},
  {"%s: option `--%s' doesn't allow an argument\n", 57},
  {"%s: option `%c%s' doesn't allow an argument\n", 58},
  {"%s: option `%s' requires an argument\n", 59},
  {"%s: unrecognized option `--%s'\n", 60},
  {"%s: unrecognized option `%c%s'\n", 61},
  {"%s: illegal option -- %c\n", 62},
  {"%s: invalid option -- %c\n", 63},
  {"%s: option requires an argument -- %c\n", 64},
  {"%s: option `-W %s' is ambiguous\n", 65},
  {"%s: option `-W %s' doesn't allow an argument\n", 66},
};

int _msg_tbl_length = 66;
